x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile.development
    args:
      RUBY_VERSION: '3.3.5'
      PG_MAJOR: '14'
      NODE_MAJOR: '21'
      YARN_VERSION: '1.13.0'
      BUNDLER_VERSION: '2.3.26'
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
    ANYCABLE_DEBUG: ${DEBUG:-0}
    ANYCABLE_RPC_HOST: 0.0.0.0:50051
  # image: rauversion/rauversion-dev:1.1.1
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/usr/src/app:cached
    - rails_cache:/usr/src/app/tmp/cache
    - packs:/usr/src/app/public/packs
  environment:
    <<: *env
    POSTGRES_HOST: host.docker.internal
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 1
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vi
  # depends_on:
  #   postgres:
  #     condition: service_healthy
  #   redis:
  #     condition: service_healthy

services:
  #runner:
  #  <<: *backend
  #  command: /bin/bash

  rails:
    <<: *backend
    command: ./bin/dev
    ports:
      - '3000:3000'
      - '3001:3001'

volumes:
  #postgres: null
  #redis: null
  # bundle: null
  # node_modules: null
  rails_cache: null
  packs: null
